version: '3.8'

services:
  backend:
    build: ./backend
    container_name: backend
    env_file: .env
    ports:
      - "127.0.0.1:8000:8000"
    depends_on:
      - db

  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    container_name: frontend
    restart: "no"
    volumes:
      - /var/www/powerbi:/deploy
    command: sh -c "npm install --legacy-peer-deps && npm run build && cp -r /app/dist/* /deploy/"


  db:
    image: postgres:15
    container_name: postgres
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
