# Generated by Django 5.2.3 on 2025-06-23 19:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0003_user_senha_alterada_em'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='usuarios_permitidos',
            field=models.ManyToManyField(blank=True, related_name='dashboards_exclusivos', to=settings.AUTH_USER_MODEL),
        ),
    ]
