# BLOCO FRONTEND
server {
    listen 80;
    server_name powerbi.laboratoriosobral.com.br;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name powerbi.laboratoriosobral.com.br;

    # Certificado SAN válido para os dois domínios
    ssl_certificate /etc/letsencrypt/live/apibi.laboratoriosobral.com.br/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/apibi.laboratoriosobral.com.br/privkey.pem;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri /index.html;
    }
}

# BLOCO API
server {
    listen 80;
    server_name apibi.laboratoriosobral.com.br;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name apibi.laboratoriosobral.com.br;

    # Mesmo certificado usado para ambos os domínios
    ssl_certificate /etc/letsencrypt/live/apibi.laboratoriosobral.com.br/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/apibi.laboratoriosobral.com.br/privkey.pem;

    location / {
        proxy_pass http://backend:8000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /static/ {
        alias /app/static/;
    }

    location /media/ {
        alias /app/media/;
    }
}
