# Generated by Django 5.2.3 on 2025-06-25 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0004_dashboard_usuarios_permitidos'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='primeiro_acesso',
            field=models.BooleanField(default=True),
        ),
    ]
